"""Contract Schemas (Pydantic v2).

CRITICAL NOTICE: THIS FILE IS FROZEN AFTER THE FIRST COMMIT.
Any modification requires a formal Pull Request with advance notice and approval
from both Person A and Person B.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Literal
from pydantic import BaseModel, ConfigDict, Field


class Intent(str, Enum):
    """Classified user intent for conversational commerce."""
    stock_query = "stock_query"
    price_query = "price_query"
    shipping_query = "shipping_query"
    other = "other"


class Product(BaseModel):
    """Product entity in the catalog."""
    model_config = ConfigDict(from_attributes=True)

    id: str
    name: str
    price: float
    category: str
    material: str
    description: str
    sizes: list[str] = Field(default_factory=list)
    colors: list[str] = Field(default_factory=list)
    image_path: str | None = None


class StockStatus(BaseModel):
    """Real-time inventory status for a specific product."""
    model_config = ConfigDict(from_attributes=True)

    product_id: str
    quantity: int
    in_stock: bool
    low_stock: bool
    posted_on_instagram: bool


class InventoryAlert(BaseModel):
    """Inventory alert generated on stock anomalies or low stock thresholds."""
    model_config = ConfigDict(from_attributes=True)

    product_id: str
    type: Literal["low_stock", "oversold", "posted_but_out_of_stock"]
    message: str
    created_at: datetime = Field(default_factory=datetime.utcnow)


class IncomingMessage(BaseModel):
    """Inbound customer message from simulated Instagram or WhatsApp webhook."""
    model_config = ConfigDict(from_attributes=True)

    message_id: str
    customer_id: str
    channel: Literal["instagram", "whatsapp"]
    text: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class AgentAction(BaseModel):
    """Structured decision and response generated by an agent."""
    model_config = ConfigDict(from_attributes=True)

    agent: Literal["commerce", "inventory", "content"] = "commerce"
    intent: Intent
    product_id: str | None = None
    response_text: str
    escalate: bool = False
    escalation_reason: str | None = None
    confidence: float = 1.0


class BrandVoiceProfile(BaseModel):
    """Brand voice specifications used by the Content Agent."""
    model_config = ConfigDict(from_attributes=True)

    tone_descriptors: list[str] = Field(default_factory=list)
    emoji_style: str
    sample_captions: list[str] = Field(default_factory=list)
    hashtags: list[str] = Field(default_factory=list)


class CaptionRequest(BaseModel):
    """Request payload to generate on-brand captions."""
    model_config = ConfigDict(from_attributes=True)

    product: Product
    image_path: str | None = None
    extra_notes: str | None = None


class CaptionResult(BaseModel):
    """Generated caption, hashtags, and style reasoning."""
    model_config = ConfigDict(from_attributes=True)

    caption: str
    hashtags: list[str] = Field(default_factory=list)
    voice_match_notes: str


class Event(BaseModel):
    """Coordination event dispatched to the LangGraph Orchestrator."""
    model_config = ConfigDict(from_attributes=True)

    type: Literal["new_dm", "new_product_photo", "low_stock"]
    payload: dict[str, Any] = Field(default_factory=dict)
